//! `macwarden catalog generate` — auto-profile unknown services and output TOML annotations.
//!
//! Scans binaries for framework linkage and telemetry strings, infers
//! categories, and outputs TOML ready for review and commit to
//! `data/annotations.toml`.

use anyhow::Result;

use macwarden_core::{ServiceCategory, ServiceInfo};
use macwarden_launchd::{binary_frameworks, binary_telemetry_scan};

use crate::commands::scan::discover_services;

// ---------------------------------------------------------------------------
// Framework → category mapping
// ---------------------------------------------------------------------------

/// Map a framework name to a service category.
///
/// ONLY domain-specific frameworks. If a binary links this framework, it IS
/// that thing. Infrastructure frameworks (Security, CoreFoundation, IOKit)
/// are deliberately excluded — everything links them.
fn framework_to_category(framework: &str) -> Option<ServiceCategory> {
    match framework {
        // ML / AI — very specific
        "AppleNeuralEngine" | "CoreML" | "NaturalLanguage" | "Speech" => {
            Some(ServiceCategory::Input)
        }
        // Audio/Video — specific to media services
        "CoreAudio"
        | "AudioToolbox"
        | "AVFoundation"
        | "CoreMedia"
        | "MediaPlayer"
        | "AudioVideoBridging"
        | "AudioServerApplication"
        | "MediaAnalysis" => Some(ServiceCategory::Media),
        // Photos — very specific
        "Photos" | "PhotoAnalysis" | "PhotoLibrary" => Some(ServiceCategory::Media),
        // Location — specific
        "CoreLocation" | "GeoServices" | "MapKit" => Some(ServiceCategory::Networking),
        // Bluetooth — specific
        "CoreBluetooth" | "IOBluetooth" => Some(ServiceCategory::Networking),
        // Network — specific
        "NetworkExtension" | "CoreWLAN" => Some(ServiceCategory::Networking),
        // Cloud — only CloudKit itself, not Accounts (too broad)
        "CloudKit" => Some(ServiceCategory::Cloud),
        // Spotlight — specific
        "CoreSpotlight" => Some(ServiceCategory::Media),
        // HomeKit — specific
        "HomeKit" => Some(ServiceCategory::Networking),
        // Accessibility — specific
        "Accessibility" | "AccessibilityBundles" => Some(ServiceCategory::Accessibility),
        // Contacts/Calendar — specific
        "AddressBook" | "Contacts" | "EventKit" | "CalendarStore" => Some(ServiceCategory::Cloud),
        // GameKit — specific
        "GameKit" | "GameController" => Some(ServiceCategory::Media),
        // Configuration/MDM — specific
        "ConfigurationProfiles" | "ManagedClient" | "DeviceManagement" => {
            Some(ServiceCategory::Cloud)
        }
        // Everything else: skip. Security, CoreFoundation, Foundation, IOKit
        // are infrastructure that tells you nothing about function.
        _ => None,
    }
}

/// Infer category from a list of frameworks (first match wins).
fn infer_from_frameworks(frameworks: &[String]) -> Option<ServiceCategory> {
    for fw in frameworks {
        if let Some(cat) = framework_to_category(fw) {
            return Some(cat);
        }
    }
    None
}

// ---------------------------------------------------------------------------
// Command
// ---------------------------------------------------------------------------

/// Run the `catalog generate` command.
///
/// Profiles all unknown services and outputs TOML annotation entries.
pub fn run(label: Option<&str>) -> Result<()> {
    let services = discover_services()?;

    let targets: Vec<&ServiceInfo> = if let Some(label) = label {
        services.iter().filter(|s| s.label == label).collect()
    } else {
        services
            .iter()
            .filter(|s| s.category == ServiceCategory::Unknown)
            .collect()
    };

    if targets.is_empty() {
        println!("No unknown services to profile.");
        return Ok(());
    }

    println!("# Auto-generated by `macwarden catalog generate`");
    println!("# Review before committing to data/annotations.toml");
    println!("# {} services profiled\n", targets.len());

    let mut categorized = 0;
    let mut with_telemetry = 0;

    for svc in &targets {
        let binary = svc
            .plist_path
            .as_ref()
            .and_then(|p| extract_binary_from_plist(p));

        let (frameworks, scan) = match &binary {
            Some(bin) => (binary_frameworks(bin), binary_telemetry_scan(bin)),
            None => (vec![], macwarden_launchd::TelemetryScan::default()),
        };

        let inferred_cat = infer_from_frameworks(&frameworks);
        let category = inferred_cat.unwrap_or(ServiceCategory::Unknown);
        if inferred_cat.is_some() {
            categorized += 1;
        }
        if scan.has_analytics {
            with_telemetry += 1;
        }

        let safety = if scan.has_analytics {
            "telemetry"
        } else {
            "optional"
        };

        // Derive a description from the binary name
        let desc = binary.as_deref().map_or_else(
            || "Apple service — binary not found".to_owned(),
            |b| {
                let name = b.rsplit('/').next().unwrap_or(b);
                format!("Apple service: {name}")
            },
        );

        println!("[[services]]");
        println!("pattern = \"{}\"", svc.label);
        println!("description = \"{desc}\"");
        println!("category = \"{category}\"");
        println!("safety = \"{safety}\"");
        if !frameworks.is_empty() {
            println!("# Frameworks: {}", frameworks.join(", "));
        }
        if scan.has_analytics {
            println!("# Telemetry: YES ({})", scan.keywords_found.join(", "));
        }
        println!();
    }

    eprintln!(
        "---\nProfiled {} services: {} categorized from frameworks, {} with telemetry strings",
        targets.len(),
        categorized,
        with_telemetry,
    );

    Ok(())
}

/// Extract binary path from a plist file.
fn extract_binary_from_plist(plist_path: &std::path::Path) -> Option<String> {
    let data = std::fs::read(plist_path).ok()?;
    let value: plist::Value = plist::from_bytes(&data).ok()?;
    let dict = value.as_dictionary()?;

    // Try ProgramArguments[0] first, then Program
    if let Some(args) = dict.get("ProgramArguments")
        && let Some(arr) = args.as_array()
        && let Some(first) = arr.first()
        && let Some(s) = first.as_string()
    {
        return Some(s.to_owned());
    }
    if let Some(prog) = dict.get("Program")
        && let Some(s) = prog.as_string()
    {
        return Some(s.to_owned());
    }
    None
}
