//! `macwarden net block / unblock` — quick rule file CRUD.
//!
//! Creates and removes deny-rule TOML files in `~/.macwarden/net-rules/`.
//! Three forms:
//! - `--app <name>` — block all traffic for an application
//! - `--app <name> --host <domain>` — block one destination within an app
//! - `--host <domain>` — block a destination globally (all apps)

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

use anyhow::{Context, Result, bail};

use net::AppDb;

// ---------------------------------------------------------------------------
// Block
// ---------------------------------------------------------------------------

/// `macwarden net block` — create a deny rule file.
pub(super) fn run_block(app: Option<&str>, host: Option<&str>) -> Result<()> {
    if app.is_none() && host.is_none() {
        bail!(
            "specify --app, --host, or both\n\
             Examples:\n  \
             macwarden net block --app Spotify\n  \
             macwarden net block --app Spotify --host scdn.co\n  \
             macwarden net block --host tracker.example.com"
        );
    }

    let app_db = AppDb::load_builtin().context("failed to load app database")?;
    let resolved_code_id = app.map(|a| resolve_app(a, &app_db)).transpose()?;

    let rules_dir = rules_dir()?;
    std::fs::create_dir_all(&rules_dir)
        .with_context(|| format!("failed to create {}", rules_dir.display()))?;

    let slug = make_slug(app, host);
    let file_path = rules_dir.join(format!("block-{slug}.toml"));

    if file_path.exists() {
        println!("Rule already exists: {}", file_path.display());
        println!("Use `macwarden net unblock` to remove it first.");
        return Ok(());
    }

    let content = generate_rule_toml(app, resolved_code_id.as_deref(), host);

    std::fs::write(&file_path, &content)
        .with_context(|| format!("failed to write {}", file_path.display()))?;

    println!("Created deny rule: {}", file_path.display());
    print_rule_summary(app, resolved_code_id.as_deref(), host);
    Ok(())
}

// ---------------------------------------------------------------------------
// Unblock
// ---------------------------------------------------------------------------

/// `macwarden net unblock` — remove a deny rule file.
pub(super) fn run_unblock(app: Option<&str>, host: Option<&str>) -> Result<()> {
    if app.is_none() && host.is_none() {
        bail!(
            "specify --app, --host, or both\n\
             Examples:\n  \
             macwarden net unblock --app Spotify\n  \
             macwarden net unblock --host tracker.example.com"
        );
    }

    let rules_dir = rules_dir()?;
    let slug = make_slug(app, host);
    let file_path = rules_dir.join(format!("block-{slug}.toml"));

    if !file_path.exists() {
        // Try scanning for a matching rule file by content
        if let Some(found) = find_matching_rule(&rules_dir, app, host)? {
            std::fs::remove_file(&found)
                .with_context(|| format!("failed to remove {}", found.display()))?;
            println!("Removed deny rule: {}", found.display());
            return Ok(());
        }
        bail!(
            "no block rule found for this combination\n\
             Use `macwarden net rules` to see all active rules"
        );
    }

    std::fs::remove_file(&file_path)
        .with_context(|| format!("failed to remove {}", file_path.display()))?;
    println!("Removed deny rule: {}", file_path.display());
    Ok(())
}

// ---------------------------------------------------------------------------
// Rule generation
// ---------------------------------------------------------------------------

/// Generate TOML content for a deny rule file.
fn generate_rule_toml(app_name: Option<&str>, code_id: Option<&str>, host: Option<&str>) -> String {
    let mut content = String::new();
    let _ = writeln!(content, "# Auto-generated by `macwarden net block`");

    // Name
    let name = match (app_name, host) {
        (Some(a), Some(h)) => format!("Block {a} -> {h}"),
        (Some(a), None) => format!("Block {a} (all traffic)"),
        (None, Some(h)) => format!("Block {h} (all apps)"),
        (None, None) => "Block rule".to_owned(),
    };
    let _ = writeln!(content, "name = \"{name}\"");

    // Process
    match code_id {
        Some(id) => {
            let _ = writeln!(content, "process = \"{id}\"");
        }
        None => {
            let _ = writeln!(content, "process = \"*\"");
        }
    }

    // Destination
    match host {
        Some(h) => {
            let _ = writeln!(content, "dest = \"{h}\"");
        }
        None => {
            let _ = writeln!(content, "dest = \"*\"");
        }
    }

    let _ = writeln!(content, "action = \"deny\"");
    let _ = writeln!(content, "enabled = true");

    content
}

// ---------------------------------------------------------------------------
// App resolution
// ---------------------------------------------------------------------------

/// Resolve an app name or code_id to a code signing identity.
///
/// Tries in order:
/// 1. Exact code_id match (if input looks like a reverse-DNS)
/// 2. AppDb name lookup
/// 3. Error with suggestions
fn resolve_app(input: &str, app_db: &AppDb) -> Result<String> {
    // If it looks like a code_id already (contains dots), use directly
    if input.contains('.') {
        if app_db.lookup(input).is_some() {
            return Ok(input.to_owned());
        }
        // Accept it anyway — user may know a code_id not in our DB
        return Ok(input.to_owned());
    }

    // Try name lookup
    if let Some(profile) = app_db.lookup_by_name(input) {
        println!(
            "Resolved \"{input}\" -> {} ({})",
            profile.name, profile.code_id
        );
        return Ok(profile.code_id.clone());
    }

    bail!(
        "unknown app: \"{input}\"\n\
         Hint: use a code signing identity (e.g. com.spotify.client) or\n\
         a name from `macwarden net apps`"
    );
}

// ---------------------------------------------------------------------------
// File helpers
// ---------------------------------------------------------------------------

/// Get the `~/.macwarden/net-rules/` directory path.
fn rules_dir() -> Result<PathBuf> {
    let home = std::env::var("HOME").context("HOME not set")?;
    Ok(PathBuf::from(home).join(".macwarden").join("net-rules"))
}

/// Generate a filesystem-safe slug from app/host combination.
fn make_slug(app: Option<&str>, host: Option<&str>) -> String {
    let raw = match (app, host) {
        (Some(a), Some(h)) => format!("{a}-{h}"),
        (Some(a), None) => a.to_owned(),
        (None, Some(h)) => h.to_owned(),
        (None, None) => "unknown".to_owned(),
    };
    raw.to_ascii_lowercase()
        .replace(|c: char| !c.is_ascii_alphanumeric() && c != '-', "-")
}

/// Scan rule files for one that matches the given app/host criteria.
fn find_matching_rule(
    rules_dir: &Path,
    app: Option<&str>,
    host: Option<&str>,
) -> Result<Option<PathBuf>> {
    let app_db = AppDb::load_builtin().context("failed to load app database")?;
    let target_code_id = app.map(|a| resolve_app(a, &app_db)).transpose()?;

    let Ok(entries) = std::fs::read_dir(rules_dir) else {
        return Ok(None);
    };

    for entry in entries {
        let entry = entry.context("failed to read directory entry")?;
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("toml") {
            continue;
        }
        let content = std::fs::read_to_string(&path)
            .with_context(|| format!("failed to read {}", path.display()))?;

        let matches_process = match &target_code_id {
            Some(id) => content.contains(&format!("process = \"{id}\"")),
            None => content.contains("process = \"*\""),
        };
        let matches_dest = match host {
            Some(h) => content.contains(&format!("dest = \"{h}\"")),
            None => content.contains("dest = \"*\""),
        };

        if matches_process && matches_dest && content.contains("action = \"deny\"") {
            return Ok(Some(path));
        }
    }
    Ok(None)
}

/// Print a summary of the created rule.
fn print_rule_summary(app: Option<&str>, code_id: Option<&str>, host: Option<&str>) {
    let process_str = code_id.unwrap_or("*");
    let dest_str = host.unwrap_or("* (all destinations)");
    println!("  Process: {process_str}");
    println!("  Dest:    {dest_str}");
    println!("  Action:  deny");
    if app.is_some() && host.is_none() {
        println!("\nAll network traffic for this app will be denied.");
    }
}

#[cfg(test)]
#[path = "net_block_test.rs"]
mod net_block_test;
